##
# In case of moving all the data.
# https://beets.readthedocs.io/en/latest/faq.html#id12
# https://discourse.beets.io/t/moving-my-music-files-to-a-different-drive/2248/6
##
library: Beets.db
directory: ../Beets

plugins:
  - info
  - the
  - inline
  - web
  - fuzzy
  - duplicates
  - unimported
  - importadded
  - types
  - edit
  # - chroma # pyacoustid
  - convert
  - replaygain
  - autobpm
  - beatport4
  - spotify
  - embedart
  - fetchart
  # - subsonicupdate

include:
  - .configs/files.yaml
  - .configs/data.yaml
  - .configs/quality.yaml
  - .configs/sources.yaml
  - .configs/display.yaml
  # - .configs/services.yaml
