directory: Musique
library: Bibliothèque.db
##
# In case of moving all the data.
# https://beets.readthedocs.io/en/latest/faq.html#id12
# https://discourse.beets.io/t/moving-my-music-files-to-a-different-drive/2248/6
##

ui:
  terminal_width: 120
  length_diff_thresh: 3
  import:
    match_header: 4
    match_details: 4
    match_tracklist: 8
    layout: newline

per_disc_numbering: true
rewrite:
  artist Muzzy: MUZZ
  artist FISHER: FISHER (OZ)
item_fields:
  is_multidisc: disctotal > 1
  label_with_catalognum: (label + " ~ " + catalognum) if catalognum else label
  first_albumartist: albumartist.split(", ")[0]
format_item: "$artist / $album / %if{$is_multidisc,$disc-}$track $title %if{$label,[$label_with_catalognum]} (%if{$bpm,$bpm})"
format_album: "$albumartist / $album %if{$is_multidisc,($disctotal)}"
paths:
  default: $first_albumartist/$album%aunique{} ($year) [$label_with_catalognum]/%if{$is_multidisc,$disc-}$track $title

import:
  write: true
  move: true
  timid: true
  log: Beets.log
  languages:
    - fr
    - en
  # group_albums: true
  bell: true

plugins:
  - info
  - inline
  - web
  - fuzzy
  - duplicates
  - unimported
  - importadded
  - types
  - edit
  - chroma # pyacoustid
  - convert
  - replaygain
  # - fromfilename
  - beatport4
  - spotify
  # - lastgenre
  # - bpmanalyser
  - lyrics
  - embedart
  - fetchart

types:
  rating: int

edit:
  itemfields:
    - disc
    - disctotal
    - track
    - title
    - artist
    - album
    - albumartist
    - cover_art_url
    - label
    - catalognum
    - genre
    - rating
    - bpm
    - key
    - comp
    - comments
  albumfields:
    - album
    - albumartist
    - cover_art_url
    - disctotal
    - label
    - catalognum
    - genre
    - comp
    - comments

convert:
  auto: false
  copy_album_art: true
  embed: true
  never_convert_lossy_files: true
  delete_originals: false
  format: flac
  # format: aiff
  formats:
    aiff:
      command: ffmpeg -i $source -write_id3v2 1 -c:v copy $dest
      extension: aiff

replaygain:
  backend: ffmpeg
  overwrite: true
  # backend: gstreamer

importadded:
  preserve_mtimes: true
  preserve_write_mtimes: true

lastgenre:
  count: 3
  source: track

bpmanalyser:
  auto: true
  write: true

embedart:
  maxwidth: 1500
  remove_art_file: false

fetchart:
  quality: 100
  sources:
    - filesystem
    - itunes
    - amazon
    - "*"
  high_resolution: true

spotify:
  source_weight: 1.0
  show_failures: true

beatport4:
  source_weight: 0.7
  art: true
  art_overwrite: false

musicbrainz:
  source_weight: 0.4
  extra_tags: [catalognum, label, year]
  external_ids:
    discogs: true
    spotify: true
    bandcamp: true
    beatport: true
    tidal: true
