spotify:
  source_weight: 1.0
  show_failures: true

beatport4:
  source_weight: 0.7
  art: true
  art_overwrite: false

musicbrainz:
  source_weight: 0.4
  extra_tags: [catalognum, label, year]
  external_ids:
    discogs: true
    spotify: true
    bandcamp: true
    beatport: true
    tidal: true
