spotify:
  # source_weight: 0.4
  data_source_mismatch_penalty: 0.6
  # show_failures: false

deezer:
  # source_weight: 0.4
  data_source_mismatch_penalty: 0.6

beatport:
  # source_weight: 0.8
  data_source_mismatch_penalty: 0.2

discogs:
  # source_weight: 0.5
  data_source_mismatch_penalty: 0.5

musicbrainz:
  # source_weight: 0.2
  data_source_mismatch_penalty: 0.8
  extra_tags: [catalognum, label, year]
  external_ids:
    discogs: true
    spotify: true
    bandcamp: true
    beatport: true
    tidal: true
