##
# In case of moving all the data.
# https://beets.readthedocs.io/en/latest/faq.html#id12
# https://discourse.beets.io/t/moving-my-music-files-to-a-different-drive/2248/6
##
directory: D:\Beets
library: Bibliothèque.db
paths:
  default: Musique/%the{$first_albumartist}/$album%aunique{} ($year)$smart_label_and_catalog_for_path/$smart_disc_and_track_numbers$title
  singleton: Musique/%the{$first_albumartist}/$album%aunique{} ($year)$smart_label_and_catalog_for_path/$title
  albumtype:DJ-mix: Mixes/%the{$first_albumartist}/$album%aunique{} ($year)$smart_label_and_catalog_for_path/$smart_disc_and_track_numbers$title
  albumtype:Soundtrack: Bandes sonores/%the{$first_albumartist}/$album%aunique{} ($year)$smart_label_and_catalog_for_path/$smart_disc_and_track_numbers$title
  comp: Compilations/%the{$first_albumartist}/$album%aunique{} ($year)$smart_label_and_catalog_for_path/$smart_disc_and_track_numbers$artist - $title

item_fields:
  smart_disc_and_track_numbers: |
    result = ""
    if albumtype.capitalize() != "Single" and albumtype.capitalize() != "Remix":
      if tracktotal > 1:
        result += str(track).zfill(2) if tracktotal >= 10 else str(track)
      if disctotal > 1 and tracktotal > 1:
        result = "-" + result
      if disctotal > 1:
        result = str(disc) + result
    return result + (" " if len(result) > 0 else "")
  smart_label_and_catalog_for_path: |
    result = ""
    if len(catalognum) > 0:
      result += catalognum
    if len(label) > 0 and len(catalognum) > 0:
      result += " @ "
    if len(label) > 0:
      result += label
    return (" " + result) if label or catalognum else ""
  first_albumartist: albumartist.split(", ")[0]

import:
  write: true
  move: true
  timid: true
  log: Beets.log
  languages:
    - fr
    - en
  bell: true
